### ISSUE TITLE
Microsoft.ML.OnnxRuntime.OnnxRuntimeException When changing Width and Height properties of a custom model.

### ISSUE THREAD

**Issue by dstampher** [mentalstack/yolov5-net#24]
Link to onnx model and test image: https://drive.google.com/file/d/12MVcF0Ir0sEnNjmKHKjDnPItvEw6l9mi/view?usp=sharing

Model works fine with detect.py, although the bounding box isn't as wide as it should be in the provided test.jpg (fixed that problem by training at a higher res, but haven't converted that .pt file to .onnx yet).

```
Unhandled exception. Microsoft.ML.OnnxRuntime.OnnxRuntimeException: [ErrorCode:InvalidArgument] Got invalid di
mensions for input: images for the following indices
 index: 2 Got: 320 Expected: 640
 index: 3 Got: 320 Expected: 640
 Please fix either the inputs or the model.
   at Microsoft.ML.OnnxRuntime.NativeApiStatus.VerifySuccess(IntPtr nativeStatus)
   at Microsoft.ML.OnnxRuntime.InferenceSession.RunImpl(RunOptions options, IntPtr[] inputNames, IntPtr[] inpu
tValues, IntPtr[] outputNames, DisposableList`1 cleanupList)
   at Microsoft.ML.OnnxRuntime.InferenceSession.Run(IReadOnlyCollection`1 inputs, IReadOnlyCollection`1 output
Names, RunOptions options)
   at Microsoft.ML.OnnxRuntime.InferenceSession.Run(IReadOnlyCollection`1 inputs, IReadOnlyCollection`1 output
Names)
   at Microsoft.ML.OnnxRuntime.InferenceSession.Run(IReadOnlyCollection`1 inputs)
   at Yolov5Net.Scorer.YoloScorer`1.Inference(Image image) in C:\Users\david\repos\yolov5-net\src\Yolov5Net.Sc
orer\YoloScorer.cs:line 131
   at Yolov5Net.Scorer.YoloScorer`1.Predict(Image image) in C:\Users\david\repos\yolov5-net\src\Yolov5Net.Scor
er\YoloScorer.cs:line 310
   at Yolov5Net.App.Program.Main(String[] args) in C:\Users\david\repos\yolov5-net\src\Yolov5Net.App\Program.c
s:line 17

Process finished with exit code -532,462,766.
```

And here is my class:

```
public class YoloCrosswalksModel : YoloModel
{
    public override int Width { get; set; } = 320;
    public override int Height { get; set; } = 320;
    public override int Depth { get; set; } = 3;

    public override int Dimensions { get; set; } = 85;

    public override float[] Strides { get; set; } = new float[] { 8, 16, 32 };

    public override float[][][] Anchors { get; set; } = new float[][][]
    {
        new float[][] { new float[] { 010, 13 }, new float[] { 016, 030 }, new float[] { 033, 023 } },
        new float[][] { new float[] { 030, 61 }, new float[] { 062, 045 }, new float[] { 059, 119 } },
        new float[][] { new float[] { 116, 90 }, new float[] { 156, 198 }, new float[] { 373, 326 } }
    };

    public override int[] Shapes { get; set; } = new int[] { 80, 40, 20 };

    public override float Confidence { get; set; } = 0.20f;
    public override float MulConfidence { get; set; } = 0.20f;
    public override float Overlap { get; set; } = 0.45f;

    public override string[] Outputs { get; set; } = new[] { "output" };

    public override List<YoloLabel> Labels { get; set; } = new List<YoloLabel>()
    {
        new YoloLabel { Id = 1, Name = "crosswalks" },
    };

    public override bool UseDetect { get; set; } = true;

    public YoloCrosswalksModel()
    {

    }
}
```

**Comment by kkarahainko** [comment]
@dstampher 

inference:

```
using var image = Image.FromFile("Assets/crosswalk.jpg");
using var scorer = new YoloScorer<CrosswalksModel>("Assets/Weights/crosswalks.onnx");
List<YoloPrediction> predictions = scorer.Predict(image);
```

model config:

```
public class CrosswalksModel : YoloModel
    {
        public override int Width { get; set; } = 640;
        public override int Height { get; set; } = 640;
        public override int Depth { get; set; } = 3;

        public override int Dimensions { get; set; } = 6;

        public override float[] Strides { get; set; } = new float[] { 8, 16, 32 };

        public override float[][][] Anchors { get; set; } = new float[][][]
        {
            new float[][] { new float[] { 010, 13 }, new float[] { 016, 030 }, new float[] { 033, 023 } },
            new float[][] { new float[] { 030, 61 }, new float[] { 062, 045 }, new float[] { 059, 119 } },
            new float[][] { new float[] { 116, 90 }, new float[] { 156, 198 }, new float[] { 373, 326 } }
        };

        public override int[] Shapes { get; set; } = new int[] { 80, 40, 20 };

        public override float Confidence { get; set; } = 0.20f;
        public override float MulConfidence { get; set; } = 0.25f;
        public override float Overlap { get; set; } = 0.45f;

        public override string[] Outputs { get; set; } = new[] { "output" };

        public override List<YoloLabel> Labels { get; set; } = new List<YoloLabel>()
        {
            new YoloLabel { Id = 0, Name = "crosswalk" }
        };

        public override bool UseDetect { get; set; } = true;

        public CrosswalksModel()
        {

        }
    }
```

result:

![result](https://user-images.githubusercontent.com/1279307/135978444-39117b38-aff5-4308-82dc-5c5c0278191c.jpg)

**Comment by kkarahainko** [comment]
@dstampher please update NuGet package or clone latest version.

**Comment by dstampher** [comment]
@kkarahainko Using newest version, it works for inference now, same exception happens when I change width/height to 320 however.  My dataset images were all 300x300 so I trained at 320x320.  

Still works at 640x640 for inference, but this inability to change width/height might be a problem for other users of this repo.

**Comment by kkarahainko** [comment]
@dstampher not sure what do you mean, you've trained your model with --img 640, inspect your onnx file with [netron.app](https://netron.app/) to be sure, you also may run Predict with any size of images. no need to change w.h to 320 In model config C# class.

**Comment by dstampher** [comment]
@kkarahainko Ah yes, sorry about that.  My 320x320 training was a previous run.  Note to self:  don't touch width/height in my class that inherits from YoloModel.  Got it.

**Comment by kkarahainko** [comment]
@dstampher no problem, you may touch it ) it depends on what size you training, for P6 models it may be 1024 for example etc, for P5 up to 640 the best option.
